#!/bin/bash

file=$(echo $1 | cut -d: -f1)
page=$(echo $1 | cut -d: -f2 | cut -d' ' -f2)

result="$(echo $1 | rev | cut -f1 -d: | rev | sed 's/[(|)]/ /g' | sed 's/[{|}]/ /g'  )"
result+="|$"

rga --pretty "" "$file" | grep "Page $page" | grep --color=always -E "$result"
