#!/bin/bash



pdfopen(){
	if [[ -z $2 ]]; then
	    [[ -z $1 ]] && printf "\n Missing Filename..."
	    printf "\n Missing Page Number...\n\n"
	    printf "   Syntax: OpenToPage Filename Page_Number\n"
	    printf "   Example: OpenToPage Filename.pdf 3\n\n"
	    exit 1
	else
	    open -a Preview "$1"
	    sleep .5
	    osascript -e 'tell application "Preview" to activate' \
		      -e 'delay 0.25' \
		      -e 'tell application "System Events" to tell process "Preview" to click menu item "Go to Page…" of menu "Go" of menu bar 1' \
		      -e 'delay 0.25' \
		      -e "tell application \"System Events\" to keystroke \"$2\"" \
		      -e 'delay 0.25' \
		      -e 'tell application "System Events" to key code 36'
	fi
	exit 0
}

pdfsearch(){
	local file="$(
		rga \
			--no-heading --smart-case \
			--color=always --colors=match:none \
			--colors=path:fg:red '.{10}' \
			-g '*.pdf' \
			--no-messages \
		|
		fzf \
			--color --ansi -i \
			--sort --preview="pdfpreview {} {q}" \
			--preview-window="30%:wrap" \
			--delimiter : --nth 2.. \
			--print-query \
			--query ${1:-''}
	)"

	local query;
	{ read query; read file; } <<< "$file"

	local f=$(echo $file | cut -d: -f1)
	local page=$(echo $file | cut -d: -f2 | cut -d' ' -f2)

	file="$(pwd)/$f"

	[[ ! -z "$f" ]] && pdfopen $file $page && pdfsearch "$query"
}


